version: "3.8"

services:
    broker:
        image: apache/kafka:latest
        container_name: broker
        environment:
            KAFKA_NODE_ID: 1
            KAFKA_PROCESS_ROLES: broker,controller
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9092
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_NUM_PARTITIONS: 3
        ports:
            - "9092:9092"
        volumes:
            - kafka-data:/var/lib/kafka/data
        networks:
            - mintrade-net

    kafka-init:
        image: apache/kafka:latest
        container_name: kafka-init
        networks:
            - mintrade-net
        depends_on:
            - broker
        volumes:
            - ./kafka/create-topics.sh:/create-topics.sh:ro
            - ./kafka/topics.txt:/topics.txt:ro
        entrypoint: [ "/bin/sh","-c","sh /create-topics.sh" ]

    mintrade-order:
        image: postgres:15
        container_name: mintrade-order
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: mintrade-order
        ports:
            - "1234:5432"
        volumes:
            - order-data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1" ]
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 10s
        networks:
            - mintrade-net

    order-init-runner:
        image: postgres:15
        container_name: order-init-runner
        depends_on:
            mintrade-order:
                condition: service_healthy
        environment:
            PGUSER: postgres
            PGPASSWORD: password
            PGDATABASE: mintrade-order
            PGHOST: mintrade-order
            SCRIPTS_DIR: /scripts
        volumes:
            - ./order/initdb.d:/scripts:ro
            - ./order/run-init.sh:/usr/local/bin/run-init.sh:ro
        entrypoint: [ "/bin/sh","-c","/usr/local/bin/run-init.sh" ]
        restart: "no"
        networks:
            - mintrade-net

    mintrade-portfolio:
        image: postgres:15
        container_name: mintrade-portfolio
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: mintrade-portfolio
        ports:
            - "1235:5432"
        volumes:
            - portfolio-data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1" ]
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 10s
        networks:
            - mintrade-net

    portfolio-init-runner:
        image: postgres:15
        container_name: portfolio-init-runner
        depends_on:
            mintrade-portfolio:
                condition: service_healthy
        environment:
            PGUSER: postgres
            PGPASSWORD: password
            PGDATABASE: mintrade-portfolio
            PGHOST: mintrade-portfolio
            SCRIPTS_DIR: /scripts
        volumes:
            - ./portfolio/initdb.d:/scripts:ro
            - ./portfolio/run-init.sh:/usr/local/bin/run-init.sh:ro
        entrypoint: [ "/bin/sh","-c","/usr/local/bin/run-init.sh" ]
        restart: "no"
        networks:
            - mintrade-net

volumes:
    kafka-data:
    order-data:
    portfolio-data:

networks:
    mintrade-net:
        driver: bridge

